version: '3'
services:
  php:
    build: .
    container_name: camagru
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www/html
      - ./data:/var/data/
    depends_on:
      - db
    networks:
      - camagru
    restart: on-failure
    privileged: true

  db:
    image: keinos/sqlite3:latest
    volumes:
      - ./data:/var/data/

networks:
  camagru:
    driver: bridge