services:
  php:
    build: .
    container_name: camagru
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
      - ./data:/var/data/
      - ./certs:/etc/apache2/certs/
    restart: on-failure
    privileged: true
    hostname: camagru.local
    env_file:
    - .env
